language: java

branches:
  only:
  - master
  - devel
  - "/^release.*/"

env:
  global:
    - secure: o2OZl3EwpJmlNBqknmUjvORfsY3uKqBIx3PGfIdLggpdiouCvoJXqSGstUElkC0cj6EoMblo0mMYMtQkewu9cklg2+gaSLBgJD3zh0VL3ERo7ivC8mohTiJPRBvFVHmgazF9SwYli2VIMmIHdE/fmfQyJGs6hPM1m7d4xDh3prMOSLqJRktZk7gkhaT4nGYTv3eRrRVdS4/ni5KGDQ2w6p3TszOrTekxgNSLpPwRyxQlTNEOrOR0Woc+4rSWdIZAcGM6IjEpJ7QwCHWuCklHpnp9sw9lQuJm7ArcWE/moVGFGWNnwOA57aq0SXgWN4Da90eRELFTvFSWJuBI+/U2B6262zXWU6un3WFniQs+lCtRtD4G/6VkMmY4f15dCAJJkFM+6lA9LWpEo7ZpPCT0XuMS9K5lezGvZmXFV8t90GHmQnvYjL1D7PpuQH73D2p3pTdXTY8lfdNpDIfjSjUwvc7zZTdazvfuCJi/mo+h9SaqReaQygnYWSyQ04k2jTS6AeuNaKquEWEDdPfGcD3uFOR0PW9zAUHtrKy4gaS07Jq8k+a1qhTHj6HPnWThG8u3Mbfaua/LH5UP9AYQjstrqn/Y+LIwrWcQcVKMmizPpig9gO3vQOr8K2GiryZTwS00wzCOYpAMj90WX+8RtNsAdeiZgtsfzcQaMhOvulkOCE0=
    - CLASSPATH=/usr/share/java/xalan-j2.jar:/usr/share/java/xercesImpl.jar:/usr/share/java/xml-resolver.jar

install:
- sudo apt-get update -q
- sudo apt-get install xsltproc
- sudo apt-get install libxml-xpath-perl
- sudo apt-get install libsaxon-java libxml-commons-resolver1.1-java libsaxon-java
  libxerces2-java
- sudo apt-get install trang
- sudo apt-get install imagemagick
- sudo apt-get install dblatex
- cp .travis/xmlc ~/.xmlc

script:
- make
- make check
- make dist

before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=snapshot/$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push https://$GITHUBTOKEN@github.com/stefanseefeld/docbook-xsl $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: HxUw4mQagxEYvb/yHOjNykxik8w+GKgezb9qmqYg09LWKDmh+thYy1k9llaXDkkHrgki2suJs5auvczsYLzYtKRIF7CU+9UkqEJWU2910Vr4zv8XmClru/cH9/p0eKdOKZ9JRKsEuNyVriyQcwewCY8vA6VpAZYvvijBI7b/ByX8TXsDIJuJ0013t3SiOvQMBJV4Kp/ss3/p/m8dqAHWbi4/mRrNK084KlX597hfebyZ5tAFl38kPYCFy8l9XELCRaceuNSXailUBZaK1oBiVsyeY/dMBTVyiB3eTKVevye9+yf7M0YRFRaJZaV/MMaPFiD1yG+WBcQECfH/krGxxOvH/x4+zHQDB128imu2nL2OMBGbc5ynVxPlE88QUejb/jbE4OW5qmUTY0iaU5aBVQ2atmPS546oMI9xuBrGjVlMFH5ltEhpA4y9FG/MvImprk3gx/+1al2cq2Gttbsqe7Xhc57q3D5DpoMSJKNVXAbgfY9U9utREFV2y9j/0rcpYUMr8F/Uh+W7cdmTYBwPSgo9z+ktzeQ2IKUHdqzxXaRjyhjpKbiIo7t9M/mKGFPlHPX/7aquitO5Ct4VyFoONLkkzZ6BCad28+sHUgT0mi3ede5OPvllLXiDRiBCoowktfWF0mpBTbCeGzaWhBFVwktvmAqL7WxWvfEgEF/0/Jk=
  file:
    - dist/docbook-xsl-snapshot.tar.bz2
    - dist/docbook-xsl-snapshot.tar.gz
    - dist/docbook-xsl-snapshot.zip
    - dist/docbook-xsl-ns-snapshot.tar.bz2
    - dist/docbook-xsl-ns-snapshot.tar.gz
    - dist/docbook-xsl-ns-snapshot.zip
    - dist/docbook-xsl-doc-snapshot.tar.bz2
    - dist/docbook-xsl-doc-snapshot.tar.gz
    - dist/docbook-xsl-doc-snapshot.zip
  on:
    repo: stefanseefeld/docbook-xsl
    branch: devel

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
    - irc://freenode#docbook
    on_success: always
    on_failure: always
